2019-05-20 13:25:58,304 - [INFO] - from play in pool-4-thread-1 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2019-05-20 13:26:40,565 - [ERROR] - from application in New I/O worker #1 


! @7c0h02bg6 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[object TweetController is not a member of package controllers]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:26:40,698 - [WARN] - from play in New I/O worker #1 
No application found at invoker init

2019-05-20 13:27:10,118 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 13:27:10,133 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 13:27:10,332 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 13:27:10,399 - [DEBUG] - from application in play-akka.actor.default-dispatcher-2 
[cors] filtering request to add cors

2019-05-20 13:27:10,434 - [INFO] - from play in play-akka.actor.default-dispatcher-5 
Starting application default Akka system.

2019-05-20 13:27:11,787 - [DEBUG] - from application in play-akka.actor.default-dispatcher-6 
[cors] filtering request to add cors

2019-05-20 13:28:10,630 - [DEBUG] - from application in play-akka.actor.default-dispatcher-6 
[cors] filtering request to add cors

2019-05-20 13:28:10,926 - [DEBUG] - from application in play-akka.actor.default-dispatcher-8 
Successfully inserted with LastError: reactivemongo.core.commands.LastError: DatabaseException['empty lastError message']

2019-05-20 13:28:13,292 - [DEBUG] - from application in play-akka.actor.default-dispatcher-8 
[cors] filtering request to add cors

2019-05-20 13:28:13,447 - [DEBUG] - from application in play-akka.actor.default-dispatcher-10 
[cors] filtering request to add cors

2019-05-20 13:28:28,364 - [DEBUG] - from application in play-akka.actor.default-dispatcher-8 
[cors] filtering request to add cors

2019-05-20 13:28:28,379 - [DEBUG] - from application in play-akka.actor.default-dispatcher-10 
Successfully inserted with LastError: reactivemongo.core.commands.LastError: DatabaseException['empty lastError message']

2019-05-20 13:28:32,329 - [DEBUG] - from application in play-akka.actor.default-dispatcher-8 
[cors] filtering request to add cors

2019-05-20 13:28:32,338 - [DEBUG] - from application in play-akka.actor.default-dispatcher-6 
Successfully inserted with LastError: reactivemongo.core.commands.LastError: DatabaseException['empty lastError message']

2019-05-20 13:28:34,364 - [DEBUG] - from application in play-akka.actor.default-dispatcher-8 
[cors] filtering request to add cors

2019-05-20 13:28:34,485 - [DEBUG] - from application in play-akka.actor.default-dispatcher-11 
[cors] filtering request to add cors

2019-05-20 13:29:44,761 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 13:29:44,851 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 13:29:44,855 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1638655106]] had already been terminated.)]

2019-05-20 13:29:45,084 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 13:29:45,085 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 13:29:45,091 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 13:29:45,103 - [DEBUG] - from application in play-akka.actor.default-dispatcher-10 
[cors] filtering request to add cors

2019-05-20 13:29:45,116 - [INFO] - from play in play-akka.actor.default-dispatcher-12 
Starting application default Akka system.

2019-05-20 13:29:45,747 - [DEBUG] - from application in play-akka.actor.default-dispatcher-12 
[cors] filtering request to add cors

2019-05-20 13:35:45,383 - [ERROR] - from application in New I/O worker #1 


! @7c0h17bfb - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[JsonFormats is already defined as object JsonFormats]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:37:24,193 - [ERROR] - from application in New I/O worker #1 


! @7c0h1d1jl - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[No Json deserializer found for type models.Word. Try to implement an implicit Reads or Format for this type.]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:39:05,251 - [ERROR] - from application in New I/O worker #1 


! @7c0h1il6i - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[No Json deserializer found for type models.Word. Try to implement an implicit Reads or Format for this type.]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:44:03,910 - [ERROR] - from application in New I/O worker #1 


! @7c0h29l1f - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[JsonFormats is already defined as object JsonFormats]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:45:56,548 - [ERROR] - from application in New I/O worker #1 


! @7c0h2g5hj - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[No Json deserializer found for type models.Word. Try to implement an implicit Reads or Format for this type.]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:46:55,301 - [ERROR] - from application in New I/O worker #1 


! @7c0h2jefe - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[No Json deserializer found for type models.Word. Try to implement an implicit Reads or Format for this type.]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:48:01,296 - [ERROR] - from application in New I/O worker #1 


! @7c0h2n85l - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value value]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:48:53,085 - [ERROR] - from application in New I/O worker #1 


! @7c0h306li - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[object Application is not a member of package controllers]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 13:49:15,123 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 13:49:15,138 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 13:49:15,139 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-547512762]] had already been terminated.)]

2019-05-20 13:49:15,350 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 13:49:15,352 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 13:49:15,359 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 13:49:15,371 - [DEBUG] - from application in play-akka.actor.default-dispatcher-10 
[cors] filtering request to add cors

2019-05-20 13:49:15,381 - [INFO] - from play in play-akka.actor.default-dispatcher-15 
Starting application default Akka system.

2019-05-20 13:49:16,013 - [DEBUG] - from application in play-akka.actor.default-dispatcher-10 
[cors] filtering request to add cors

2019-05-20 13:49:21,980 - [DEBUG] - from application in play-akka.actor.default-dispatcher-16 
[cors] filtering request to add cors

2019-05-20 14:02:07,619 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:02:07,690 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:02:07,692 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#1839608636]] had already been terminated.)]

2019-05-20 14:02:07,924 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:02:07,925 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:02:07,944 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:02:07,980 - [DEBUG] - from application in play-akka.actor.default-dispatcher-17 
[cors] filtering request to add cors

2019-05-20 14:02:07,992 - [INFO] - from play in play-akka.actor.default-dispatcher-18 
Starting application default Akka system.

2019-05-20 14:02:08,115 - [DEBUG] - from application in play-akka.actor.default-dispatcher-17 
[cors] filtering request to add cors

2019-05-20 14:03:44,537 - [ERROR] - from application in New I/O worker #4 


! @7c0h4ope8 - Internal server error, for (GET) [/tweets/] ->

play.PlayExceptions$CompilationException: Compilation error[Cannot write an instance of scala.concurrent.Future[play.api.libs.json.JsArray] to HTTP response. Try to define a Writeable[scala.concurrent.Future[play.api.libs.json.JsArray]]]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:04:37,741 - [ERROR] - from application in New I/O worker #4 


! @7c0h5206g - Internal server error, for (GET) [/tweets/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : scala.concurrent.Future[play.api.libs.json.JsArray]
 required: String]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:05:11,557 - [ERROR] - from application in New I/O worker #4 


! @7c0h53o76 - Internal server error, for (GET) [/tweets/] ->

play.PlayExceptions$CompilationException: Compilation error[identifier expected but integer literal found.]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:05:28,200 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:05:28,234 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:05:28,235 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#475645322]] had already been terminated.)]

2019-05-20 14:05:28,280 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:05:28,281 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:05:28,287 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:05:28,310 - [DEBUG] - from application in play-akka.actor.default-dispatcher-18 
[cors] filtering request to add cors

2019-05-20 14:05:28,321 - [INFO] - from play in play-akka.actor.default-dispatcher-20 
Starting application default Akka system.

2019-05-20 14:05:28,510 - [DEBUG] - from application in play-akka.actor.default-dispatcher-18 
[cors] filtering request to add cors

2019-05-20 14:07:10,269 - [ERROR] - from application in New I/O worker #4 


! @7c0h5ahn2 - Internal server error, for (GET) [/tweets/] ->

play.PlayExceptions$CompilationException: Compilation error[Cannot write an instance of List[models.Word] to HTTP response. Try to define a Writeable[List[models.Word]]]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:12:02,925 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:12:02,936 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:12:02,938 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1304681237]] had already been terminated.)]

2019-05-20 14:12:03,155 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:12:03,155 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:12:03,162 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:12:03,185 - [DEBUG] - from application in play-akka.actor.default-dispatcher-20 
[cors] filtering request to add cors

2019-05-20 14:12:03,197 - [INFO] - from play in play-akka.actor.default-dispatcher-22 
Starting application default Akka system.

2019-05-20 14:12:03,398 - [DEBUG] - from application in play-akka.actor.default-dispatcher-20 
[cors] filtering request to add cors

2019-05-20 14:12:05,360 - [DEBUG] - from application in play-akka.actor.default-dispatcher-20 
[cors] filtering request to add cors

2019-05-20 14:12:28,939 - [DEBUG] - from application in play-akka.actor.default-dispatcher-24 
[cors] filtering request to add cors

2019-05-20 14:12:29,069 - [DEBUG] - from application in play-akka.actor.default-dispatcher-24 
[cors] filtering request to add cors

2019-05-20 14:12:29,885 - [DEBUG] - from application in play-akka.actor.default-dispatcher-25 
[cors] filtering request to add cors

2019-05-20 14:12:29,966 - [DEBUG] - from application in play-akka.actor.default-dispatcher-23 
[cors] filtering request to add cors

2019-05-20 14:12:30,096 - [DEBUG] - from application in play-akka.actor.default-dispatcher-23 
[cors] filtering request to add cors

2019-05-20 14:12:30,173 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:12:30,281 - [DEBUG] - from application in play-akka.actor.default-dispatcher-23 
[cors] filtering request to add cors

2019-05-20 14:12:30,404 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:12:30,445 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:12:30,656 - [DEBUG] - from application in play-akka.actor.default-dispatcher-24 
[cors] filtering request to add cors

2019-05-20 14:12:54,156 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:12:54,178 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:12:54,178 - [INFO] - from application in ForkJoinPool-3-worker-5 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#1980938842]] had already been terminated.)]

2019-05-20 14:12:54,226 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:12:54,227 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:12:54,233 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:12:54,252 - [DEBUG] - from application in play-akka.actor.default-dispatcher-25 
[cors] filtering request to add cors

2019-05-20 14:12:54,262 - [INFO] - from play in play-akka.actor.default-dispatcher-26 
Starting application default Akka system.

2019-05-20 14:12:54,924 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:20:17,267 - [ERROR] - from application in New I/O worker #6 


! @7c0h73c26 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[Overloaded method value [async] cannot be applied to  (play.api.mvc.Result)]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:22:37,083 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:22:37,134 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:22:37,134 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-458752503]] had already been terminated.)]

2019-05-20 14:22:37,310 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:22:37,310 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:22:37,317 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:22:37,336 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:22:37,346 - [INFO] - from play in play-akka.actor.default-dispatcher-28 
Starting application default Akka system.

2019-05-20 14:22:37,520 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:23:14,787 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:23:14,806 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:23:14,806 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1162265071]] had already been terminated.)]

2019-05-20 14:23:14,850 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:23:14,850 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:23:14,856 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:23:14,862 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:23:17,121 - [DEBUG] - from application in play-akka.actor.default-dispatcher-30 
[cors] filtering request to add cors

2019-05-20 14:23:17,129 - [INFO] - from play in play-akka.actor.default-dispatcher-32 
Starting application default Akka system.

2019-05-20 14:23:17,818 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:23:19,666 - [DEBUG] - from application in play-akka.actor.default-dispatcher-33 
[cors] filtering request to add cors

2019-05-20 14:23:19,766 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:23:20,350 - [DEBUG] - from application in play-akka.actor.default-dispatcher-30 
[cors] filtering request to add cors

2019-05-20 14:23:20,456 - [DEBUG] - from application in play-akka.actor.default-dispatcher-31 
[cors] filtering request to add cors

2019-05-20 14:23:20,564 - [DEBUG] - from application in play-akka.actor.default-dispatcher-30 
[cors] filtering request to add cors

2019-05-20 14:23:20,668 - [DEBUG] - from application in play-akka.actor.default-dispatcher-33 
[cors] filtering request to add cors

2019-05-20 14:23:20,838 - [DEBUG] - from application in play-akka.actor.default-dispatcher-30 
[cors] filtering request to add cors

2019-05-20 14:23:20,988 - [DEBUG] - from application in play-akka.actor.default-dispatcher-26 
[cors] filtering request to add cors

2019-05-20 14:25:00,558 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:25:00,592 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:25:00,592 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-477011032]] had already been terminated.)]

2019-05-20 14:25:00,786 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:25:00,786 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:25:00,793 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:25:00,813 - [DEBUG] - from application in play-akka.actor.default-dispatcher-32 
[cors] filtering request to add cors

2019-05-20 14:25:00,826 - [INFO] - from play in play-akka.actor.default-dispatcher-34 
Starting application default Akka system.

2019-05-20 14:25:01,495 - [DEBUG] - from application in play-akka.actor.default-dispatcher-35 
[cors] filtering request to add cors

2019-05-20 14:25:07,094 - [DEBUG] - from application in play-akka.actor.default-dispatcher-32 
[cors] filtering request to add cors

2019-05-20 14:25:08,948 - [DEBUG] - from application in play-akka.actor.default-dispatcher-32 
[cors] filtering request to add cors

2019-05-20 14:25:09,065 - [DEBUG] - from application in play-akka.actor.default-dispatcher-35 
[cors] filtering request to add cors

2019-05-20 14:25:25,296 - [DEBUG] - from application in play-akka.actor.default-dispatcher-34 
[cors] filtering request to add cors

2019-05-20 14:25:32,281 - [DEBUG] - from application in play-akka.actor.default-dispatcher-34 
[cors] filtering request to add cors

2019-05-20 14:25:49,422 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
[cors] filtering request to add cors

2019-05-20 14:29:06,759 - [ERROR] - from application in New I/O worker #6 


! @7c0h87f98 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.mvc.Result
 required: play.api.libs.json.JsArray]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:29:18,744 - [ERROR] - from application in New I/O worker #6 


! @7c0h88726 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.mvc.Result
 required: play.api.libs.json.JsArray]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:30:33,450 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:30:33,471 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:30:33,471 - [INFO] - from application in ForkJoinPool-3-worker-5 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#225707969]] had already been terminated.)]

2019-05-20 14:30:33,678 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:30:33,678 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:30:33,685 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:30:33,706 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
[cors] filtering request to add cors

2019-05-20 14:30:33,717 - [INFO] - from play in play-akka.actor.default-dispatcher-38 
Starting application default Akka system.

2019-05-20 14:30:33,876 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
[cors] filtering request to add cors

2019-05-20 14:30:51,093 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:30:51,102 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:30:51,107 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-330423892]] had already been terminated.)]

2019-05-20 14:30:51,147 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:30:51,147 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:30:51,154 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:30:51,170 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
[cors] filtering request to add cors

2019-05-20 14:30:51,180 - [INFO] - from play in play-akka.actor.default-dispatcher-38 
Starting application default Akka system.

2019-05-20 14:30:51,355 - [DEBUG] - from application in play-akka.actor.default-dispatcher-40 
[cors] filtering request to add cors

2019-05-20 14:36:35,189 - [ERROR] - from application in New I/O worker #7 


! @7c0h972ig - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : String
 required: (String, play.api.libs.json.Json.JsValueWrapper)]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:38:43,630 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:38:43,658 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:38:43,659 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1505055368]] had already been terminated.)]

2019-05-20 14:38:43,703 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:38:43,703 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:38:43,711 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:38:43,731 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
[cors] filtering request to add cors

2019-05-20 14:38:43,741 - [INFO] - from play in play-akka.actor.default-dispatcher-42 
Starting application default Akka system.

2019-05-20 14:38:43,968 - [DEBUG] - from application in play-akka.actor.default-dispatcher-37 
[cors] filtering request to add cors

2019-05-20 14:38:56,284 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:38:56,328 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:38:56,328 - [INFO] - from application in ForkJoinPool-3-worker-1 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#550315564]] had already been terminated.)]

2019-05-20 14:38:56,382 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:38:56,393 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:38:56,399 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:38:56,412 - [DEBUG] - from application in play-akka.actor.default-dispatcher-42 
[cors] filtering request to add cors

2019-05-20 14:38:56,421 - [INFO] - from play in play-akka.actor.default-dispatcher-43 
Starting application default Akka system.

2019-05-20 14:38:57,051 - [DEBUG] - from application in play-akka.actor.default-dispatcher-42 
[cors] filtering request to add cors

2019-05-20 14:42:22,035 - [ERROR] - from application in New I/O worker #7 


! @7c0ha0lkm - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.libs.json.JsValue
 required: String]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:42:39,493 - [ERROR] - from application in New I/O worker #7 


! @7c0ha1lg7 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[value value is not a member of play.api.libs.json.JsValue]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:43:34,750 - [ERROR] - from application in New I/O worker #7 


! @7c0ha4p9f - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.libs.json.JsResult[scala.concurrent.Future[play.api.mvc.Result]]
 required: scala.concurrent.Future[play.api.mvc.Result]]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:44:22,779 - [ERROR] - from application in New I/O worker #7 


! @7c0ha7iam - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : models.Word
 required: String]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:44:35,087 - [ERROR] - from application in New I/O worker #7 


! @7c0ha8ag5 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value value]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:45:29,049 - [ERROR] - from application in New I/O worker #7 


! @7c0habcbh - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.libs.json.JsResult[scala.concurrent.Future[play.api.mvc.Result]]
 required: scala.concurrent.Future[play.api.mvc.Result]]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:45:50,225 - [ERROR] - from application in New I/O worker #7 


! @7c0hachk4 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.libs.json.JsResult[scala.concurrent.Future[play.api.mvc.Result]]
 required: scala.concurrent.Future[play.api.mvc.Result]]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:47:12,590 - [ERROR] - from application in New I/O worker #7 


! @7c0hah9g1 - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : play.api.libs.json.JsResult[scala.concurrent.Future[play.api.mvc.Result]]
 required: scala.concurrent.Future[play.api.mvc.Result]]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:48:16,065 - [ERROR] - from application in New I/O worker #7 


! @7c0hakpda - Internal server error, for (GET) [/words/] ->

play.PlayExceptions$CompilationException: Compilation error[method store is defined twice
  conflicting symbols both originated in file '/Users/diego/Sites/lab-2-distribuidos/backend-2/app/controllers/WordController.scala']
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:48:31,781 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:48:31,796 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:48:31,800 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#1972028730]] had already been terminated.)]

2019-05-20 14:48:31,988 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:48:31,988 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:48:31,993 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:48:32,005 - [DEBUG] - from application in play-akka.actor.default-dispatcher-43 
[cors] filtering request to add cors

2019-05-20 14:48:32,025 - [INFO] - from play in play-akka.actor.default-dispatcher-45 
Starting application default Akka system.

2019-05-20 14:48:32,633 - [DEBUG] - from application in play-akka.actor.default-dispatcher-46 
[cors] filtering request to add cors

2019-05-20 14:48:52,065 - [DEBUG] - from application in play-akka.actor.default-dispatcher-45 
[cors] filtering request to add cors

2019-05-20 14:48:52,136 - [DEBUG] - from application in play-akka.actor.default-dispatcher-45 
Successfully removed with LastError: reactivemongo.core.commands.LastError: DatabaseException['empty lastError message']

2019-05-20 14:48:53,434 - [DEBUG] - from application in play-akka.actor.default-dispatcher-43 
[cors] filtering request to add cors

2019-05-20 14:48:53,528 - [DEBUG] - from application in play-akka.actor.default-dispatcher-43 
[cors] filtering request to add cors

2019-05-20 14:52:11,420 - [DEBUG] - from application in play-akka.actor.default-dispatcher-47 
[cors] filtering request to add cors

2019-05-20 14:52:21,274 - [DEBUG] - from application in play-akka.actor.default-dispatcher-51 
[cors] filtering request to add cors

2019-05-20 14:52:35,123 - [DEBUG] - from application in play-akka.actor.default-dispatcher-47 
[cors] filtering request to add cors

2019-05-20 14:52:49,130 - [DEBUG] - from application in play-akka.actor.default-dispatcher-49 
[cors] filtering request to add cors

2019-05-20 14:52:49,148 - [ERROR] - from play in play-akka.actor.default-dispatcher-51 
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))

2019-05-20 14:52:49,170 - [ERROR] - from application in play-akka.actor.default-dispatcher-51 


! @7c0hbadda - Internal server error, for (GET) [/tweets/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.2.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
Caused by: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:355) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:348) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.2.jar:na]
	... 4 common frames omitted

2019-05-20 14:52:54,050 - [DEBUG] - from application in play-akka.actor.default-dispatcher-51 
[cors] filtering request to add cors

2019-05-20 14:52:54,062 - [ERROR] - from play in play-akka.actor.default-dispatcher-54 
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))

2019-05-20 14:52:54,065 - [ERROR] - from application in play-akka.actor.default-dispatcher-54 


! @7c0hbakjj - Internal server error, for (GET) [/tweets/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.2.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
Caused by: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:355) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:348) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.2.jar:na]
	... 2 common frames omitted

2019-05-20 14:53:28,382 - [DEBUG] - from application in play-akka.actor.default-dispatcher-51 
[cors] filtering request to add cors

2019-05-20 14:53:28,388 - [ERROR] - from play in play-akka.actor.default-dispatcher-49 
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))

2019-05-20 14:53:28,391 - [ERROR] - from application in play-akka.actor.default-dispatcher-49 


! @7c0hbcjdp - Internal server error, for (GET) [/tweets/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.2.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
Caused by: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:355) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:348) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.2.jar:na]
	... 2 common frames omitted

2019-05-20 14:54:25,011 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:54:25,026 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:54:25,027 - [INFO] - from application in ForkJoinPool-3-worker-1 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1674828920]] had already been terminated.)]

2019-05-20 14:54:25,279 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:54:25,280 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:54:25,293 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:54:25,308 - [DEBUG] - from application in play-akka.actor.default-dispatcher-51 
[cors] filtering request to add cors

2019-05-20 14:54:25,319 - [INFO] - from play in play-akka.actor.default-dispatcher-57 
Starting application default Akka system.

2019-05-20 14:54:25,347 - [ERROR] - from play in play-akka.actor.default-dispatcher-57 
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))

2019-05-20 14:54:25,349 - [ERROR] - from application in play-akka.actor.default-dispatcher-57 


! @7c0hbfpkh - Internal server error, for (GET) [/tweets/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.2.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
Caused by: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:355) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:348) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.2.jar:na]
	... 2 common frames omitted

2019-05-20 14:57:15,889 - [DEBUG] - from application in play-akka.actor.default-dispatcher-58 
[cors] filtering request to add cors

2019-05-20 14:57:15,997 - [DEBUG] - from application in play-akka.actor.default-dispatcher-60 
[cors] filtering request to add cors

2019-05-20 14:58:31,942 - [ERROR] - from application in New I/O worker #7 


! @7c0hc40ep - Internal server error, for (GET) [/tweets/word] ->

play.PlayExceptions$CompilationException: Compilation error[')' expected but string literal found.]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:58:42,936 - [ERROR] - from application in New I/O worker #7 


! @7c0hc4gll - Internal server error, for (GET) [/tweets/word] ->

play.PlayExceptions$CompilationException: Compilation error[value getByWord is not a member of object controllers.TweetController]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 14:59:03,844 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 14:59:03,895 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 14:59:03,895 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#1291800865]] had already been terminated.)]

2019-05-20 14:59:03,930 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 14:59:03,931 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 14:59:03,937 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 14:59:03,952 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
[cors] filtering request to add cors

2019-05-20 14:59:03,962 - [INFO] - from play in play-akka.actor.default-dispatcher-63 
Starting application default Akka system.

2019-05-20 14:59:04,573 - [DEBUG] - from application in play-akka.actor.default-dispatcher-64 
[cors] filtering request to add cors

2019-05-20 14:59:10,478 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
[cors] filtering request to add cors

2019-05-20 15:59:50,516 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
[cors] filtering request to add cors

2019-05-20 15:59:50,644 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
[cors] filtering request to add cors

2019-05-20 15:59:53,058 - [DEBUG] - from application in play-akka.actor.default-dispatcher-62 
[cors] filtering request to add cors

2019-05-20 15:59:53,061 - [ERROR] - from play in play-akka.actor.default-dispatcher-68 
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))

2019-05-20 15:59:53,063 - [ERROR] - from application in play-akka.actor.default-dispatcher-68 


! @7c0hk5c0f - Internal server error, for (GET) [/tweets/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.2.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.6.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
Caused by: java.lang.RuntimeException: JsError(List((/value,List(ValidationError(error.path.missing,WrappedArray())))))
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:355) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:348) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:670) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.2.jar:na]
	... 2 common frames omitted

2019-05-20 16:02:06,773 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:02:06,791 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:02:06,793 - [INFO] - from application in ForkJoinPool-3-worker-5 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1654467686]] had already been terminated.)]

2019-05-20 16:02:07,050 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:02:07,050 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:02:07,054 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:02:07,067 - [DEBUG] - from application in play-akka.actor.default-dispatcher-67 
[cors] filtering request to add cors

2019-05-20 16:02:07,076 - [INFO] - from play in play-akka.actor.default-dispatcher-70 
Starting application default Akka system.

2019-05-20 16:02:07,240 - [DEBUG] - from application in play-akka.actor.default-dispatcher-67 
[cors] filtering request to add cors

2019-05-20 16:02:19,621 - [DEBUG] - from application in play-akka.actor.default-dispatcher-70 
[cors] filtering request to add cors

2019-05-20 16:06:09,070 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:06:09,133 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:06:09,133 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-615150944]] had already been terminated.)]

2019-05-20 16:06:09,339 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:06:09,340 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:06:09,346 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:06:09,358 - [DEBUG] - from application in play-akka.actor.default-dispatcher-70 
[cors] filtering request to add cors

2019-05-20 16:06:09,368 - [INFO] - from play in play-akka.actor.default-dispatcher-73 
Starting application default Akka system.

2019-05-20 16:06:09,975 - [DEBUG] - from application in play-akka.actor.default-dispatcher-70 
[cors] filtering request to add cors

2019-05-20 16:16:55,273 - [DEBUG] - from application in play-akka.actor.default-dispatcher-70 
[cors] filtering request to add cors

2019-05-20 16:17:07,179 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:17:07,193 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:17:07,193 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-37226176]] had already been terminated.)]

2019-05-20 16:17:07,368 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:17:07,369 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:17:07,376 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:17:07,395 - [DEBUG] - from application in play-akka.actor.default-dispatcher-78 
[cors] filtering request to add cors

2019-05-20 16:17:07,403 - [INFO] - from play in play-akka.actor.default-dispatcher-77 
Starting application default Akka system.

2019-05-20 16:17:07,545 - [DEBUG] - from application in play-akka.actor.default-dispatcher-78 
[cors] filtering request to add cors

2019-05-20 16:24:24,437 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:24:24,453 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:24:24,454 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#369531825]] had already been terminated.)]

2019-05-20 16:24:24,637 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:24:24,637 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:24:24,644 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:24:24,665 - [DEBUG] - from application in play-akka.actor.default-dispatcher-77 
[cors] filtering request to add cors

2019-05-20 16:24:24,677 - [INFO] - from play in play-akka.actor.default-dispatcher-79 
Starting application default Akka system.

2019-05-20 16:24:24,831 - [DEBUG] - from application in play-akka.actor.default-dispatcher-77 
[cors] filtering request to add cors

2019-05-20 16:31:14,397 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:31:14,416 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:31:14,417 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#1840281720]] had already been terminated.)]

2019-05-20 16:31:14,584 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:31:14,584 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:31:14,591 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:31:14,619 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
[cors] filtering request to add cors

2019-05-20 16:31:14,630 - [INFO] - from play in play-akka.actor.default-dispatcher-82 
Starting application default Akka system.

2019-05-20 16:31:14,821 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
[cors] filtering request to add cors

2019-05-20 16:31:42,091 - [ERROR] - from application in New I/O worker #8 


! @7c0hoa20i - Internal server error, for (GET) [/tweets/el] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : scala.util.matching.Regex
 required: play.api.libs.json.Json.JsValueWrapper]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 16:32:26,588 - [ERROR] - from application in New I/O worker #8 


! @7c0hocfln - Internal server error, for (GET) [/tweets/el] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : scala.util.matching.Regex
 required: play.api.libs.json.Json.JsValueWrapper]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 16:32:50,582 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:32:50,599 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:32:50,600 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1926514617]] had already been terminated.)]

2019-05-20 16:32:50,627 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:32:50,627 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:32:50,633 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:32:50,649 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
[cors] filtering request to add cors

2019-05-20 16:32:50,657 - [INFO] - from play in play-akka.actor.default-dispatcher-85 
Starting application default Akka system.

2019-05-20 16:32:51,259 - [DEBUG] - from application in play-akka.actor.default-dispatcher-85 
[cors] filtering request to add cors

2019-05-20 16:37:45,708 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:37:45,738 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:37:45,740 - [INFO] - from application in ForkJoinPool-3-worker-5 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-126980311]] had already been terminated.)]

2019-05-20 16:37:45,970 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:37:45,970 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:37:45,975 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:37:45,989 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
[cors] filtering request to add cors

2019-05-20 16:37:45,996 - [INFO] - from play in play-akka.actor.default-dispatcher-87 
Starting application default Akka system.

2019-05-20 16:37:46,588 - [DEBUG] - from application in play-akka.actor.default-dispatcher-80 
[cors] filtering request to add cors

2019-05-20 16:39:35,778 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:39:35,837 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:39:35,838 - [INFO] - from application in ForkJoinPool-3-worker-5 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#400226051]] had already been terminated.)]

2019-05-20 16:39:35,870 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:39:35,870 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:39:35,875 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:39:35,890 - [DEBUG] - from application in play-akka.actor.default-dispatcher-87 
[cors] filtering request to add cors

2019-05-20 16:39:35,898 - [INFO] - from play in play-akka.actor.default-dispatcher-90 
Starting application default Akka system.

2019-05-20 16:39:36,477 - [DEBUG] - from application in play-akka.actor.default-dispatcher-91 
[cors] filtering request to add cors

2019-05-20 16:40:40,051 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:40:40,068 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:40:40,068 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-1591705039]] had already been terminated.)]

2019-05-20 16:40:40,096 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:40:40,097 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:40:40,101 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:40:40,117 - [DEBUG] - from application in play-akka.actor.default-dispatcher-87 
[cors] filtering request to add cors

2019-05-20 16:40:40,126 - [INFO] - from play in play-akka.actor.default-dispatcher-92 
Starting application default Akka system.

2019-05-20 16:40:40,761 - [DEBUG] - from application in play-akka.actor.default-dispatcher-87 
[cors] filtering request to add cors

2019-05-20 16:40:54,614 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:40:54,634 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:40:54,635 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-2060463267]] had already been terminated.)]

2019-05-20 16:40:54,666 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:40:54,667 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:40:54,683 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:40:54,701 - [DEBUG] - from application in play-akka.actor.default-dispatcher-93 
[cors] filtering request to add cors

2019-05-20 16:40:54,711 - [INFO] - from play in play-akka.actor.default-dispatcher-92 
Starting application default Akka system.

2019-05-20 16:40:55,362 - [DEBUG] - from application in play-akka.actor.default-dispatcher-94 
[cors] filtering request to add cors

2019-05-20 16:41:28,964 - [ERROR] - from application in New I/O worker #8 


! @7c0hphc4j - Internal server error, for (GET) [/tweets/el] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : reactivemongo.api.Cursor[models.Tweet]
 required: String]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 16:41:41,665 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:41:41,679 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:41:41,680 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-2114369321]] had already been terminated.)]

2019-05-20 16:41:41,882 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:41:41,883 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:41:41,889 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:41:41,899 - [DEBUG] - from application in play-akka.actor.default-dispatcher-95 
[cors] filtering request to add cors

2019-05-20 16:41:41,906 - [INFO] - from play in play-akka.actor.default-dispatcher-92 
Starting application default Akka system.

2019-05-20 16:41:42,532 - [DEBUG] - from application in play-akka.actor.default-dispatcher-92 
[cors] filtering request to add cors

2019-05-20 16:43:05,460 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:43:05,477 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:43:05,477 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-240113413]] had already been terminated.)]

2019-05-20 16:43:05,512 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:43:05,515 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:43:05,521 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:43:05,543 - [DEBUG] - from application in play-akka.actor.default-dispatcher-95 
[cors] filtering request to add cors

2019-05-20 16:43:05,552 - [INFO] - from play in play-akka.actor.default-dispatcher-97 
Starting application default Akka system.

2019-05-20 16:43:12,121 - [DEBUG] - from application in play-akka.actor.default-dispatcher-97 
[cors] filtering request to add cors

2019-05-20 16:43:27,549 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:43:27,569 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:43:27,570 - [INFO] - from application in ForkJoinPool-3-worker-1 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#355875402]] had already been terminated.)]

2019-05-20 16:43:27,600 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:43:27,601 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:43:27,607 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:43:27,624 - [DEBUG] - from application in play-akka.actor.default-dispatcher-95 
[cors] filtering request to add cors

2019-05-20 16:43:27,646 - [INFO] - from play in play-akka.actor.default-dispatcher-98 
Starting application default Akka system.

2019-05-20 16:43:27,852 - [DEBUG] - from application in play-akka.actor.default-dispatcher-97 
[cors] filtering request to add cors

2019-05-20 16:44:52,569 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:44:52,587 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:44:52,588 - [INFO] - from application in ForkJoinPool-3-worker-3 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-291380942]] had already been terminated.)]

2019-05-20 16:44:52,857 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:44:52,857 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:44:52,864 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:44:52,873 - [DEBUG] - from application in play-akka.actor.default-dispatcher-100 
[cors] filtering request to add cors

2019-05-20 16:44:52,881 - [INFO] - from play in play-akka.actor.default-dispatcher-101 
Starting application default Akka system.

2019-05-20 16:44:53,044 - [DEBUG] - from application in play-akka.actor.default-dispatcher-102 
[cors] filtering request to add cors

2019-05-20 16:45:23,920 - [ERROR] - from application in New I/O worker #8 


! @7c0i04ljd - Internal server error, for (GET) [/tweets/by-word/MBI] ->

play.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : String
 required: (String, play.api.libs.json.Json.JsValueWrapper)]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.2.jar:na]

2019-05-20 16:45:45,112 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:45:45,131 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:45:45,131 - [INFO] - from application in ForkJoinPool-3-worker-7 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-602235206]] had already been terminated.)]

2019-05-20 16:45:45,166 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:45:45,167 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:45:45,174 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:45:45,190 - [DEBUG] - from application in play-akka.actor.default-dispatcher-100 
[cors] filtering request to add cors

2019-05-20 16:45:45,199 - [INFO] - from play in play-akka.actor.default-dispatcher-104 
Starting application default Akka system.

2019-05-20 16:45:45,827 - [DEBUG] - from application in play-akka.actor.default-dispatcher-104 
[cors] filtering request to add cors

2019-05-20 16:54:01,167 - [INFO] - from play in play-internal-execution-context-1 
Shutdown application default Akka system.

2019-05-20 16:54:01,192 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin stops, closing connections...

2019-05-20 16:54:01,193 - [INFO] - from application in ForkJoinPool-3-worker-5 
ReactiveMongo Connections stopped. [Failure(akka.pattern.AskTimeoutException: Recipient[Actor[akka://application/user/$b#-952337885]] had already been terminated.)]

2019-05-20 16:54:01,363 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin starting...

2019-05-20 16:54:01,364 - [INFO] - from application in play-internal-execution-context-1 
ReactiveMongoPlugin successfully started with db 'distribuidos'! Servers:
		[localhost:27017]

2019-05-20 16:54:01,368 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2019-05-20 16:54:01,391 - [DEBUG] - from application in play-akka.actor.default-dispatcher-104 
[cors] filtering request to add cors

2019-05-20 16:54:01,398 - [INFO] - from play in play-akka.actor.default-dispatcher-106 
Starting application default Akka system.

2019-05-20 16:54:23,524 - [DEBUG] - from application in play-akka.actor.default-dispatcher-106 
[cors] filtering request to add cors

2019-05-20 16:55:51,272 - [DEBUG] - from application in play-akka.actor.default-dispatcher-106 
[cors] filtering request to add cors

2019-05-20 16:56:49,313 - [DEBUG] - from application in play-akka.actor.default-dispatcher-111 
[cors] filtering request to add cors

2019-05-20 16:57:24,026 - [DEBUG] - from application in play-akka.actor.default-dispatcher-115 
[cors] filtering request to add cors

2019-05-20 17:02:06,572 - [DEBUG] - from application in play-akka.actor.default-dispatcher-116 
[cors] filtering request to add cors

2019-05-20 17:06:47,944 - [DEBUG] - from application in play-akka.actor.default-dispatcher-116 
[cors] filtering request to add cors

2019-05-20 17:06:59,503 - [DEBUG] - from application in play-akka.actor.default-dispatcher-116 
[cors] filtering request to add cors

2019-05-20 17:07:52,331 - [DEBUG] - from application in play-akka.actor.default-dispatcher-122 
[cors] filtering request to add cors

2019-05-20 17:08:01,085 - [DEBUG] - from application in play-akka.actor.default-dispatcher-126 
[cors] filtering request to add cors

2019-05-20 17:08:50,964 - [DEBUG] - from application in play-akka.actor.default-dispatcher-126 
[cors] filtering request to add cors

2019-05-20 17:09:05,485 - [DEBUG] - from application in play-akka.actor.default-dispatcher-127 
[cors] filtering request to add cors

2019-05-20 17:11:44,806 - [DEBUG] - from application in play-akka.actor.default-dispatcher-127 
[cors] filtering request to add cors

2019-05-20 17:13:15,613 - [DEBUG] - from application in play-akka.actor.default-dispatcher-131 
[cors] filtering request to add cors

2019-05-20 17:13:27,225 - [DEBUG] - from application in play-akka.actor.default-dispatcher-134 
[cors] filtering request to add cors

2019-05-20 17:13:46,874 - [DEBUG] - from application in play-akka.actor.default-dispatcher-134 
[cors] filtering request to add cors

2019-05-20 17:20:21,470 - [DEBUG] - from application in play-akka.actor.default-dispatcher-133 
[cors] filtering request to add cors

2019-05-20 17:20:27,327 - [DEBUG] - from application in play-akka.actor.default-dispatcher-137 
[cors] filtering request to add cors

2019-05-20 17:21:32,261 - [DEBUG] - from application in play-akka.actor.default-dispatcher-138 
[cors] filtering request to add cors

2019-05-20 17:27:04,468 - [DEBUG] - from application in play-akka.actor.default-dispatcher-138 
[cors] filtering request to add cors

2019-05-20 17:28:56,906 - [DEBUG] - from application in play-akka.actor.default-dispatcher-144 
[cors] filtering request to add cors

2019-05-20 17:29:11,082 - [DEBUG] - from application in play-akka.actor.default-dispatcher-144 
[cors] filtering request to add cors

2019-05-20 17:30:35,586 - [DEBUG] - from application in play-akka.actor.default-dispatcher-147 
[cors] filtering request to add cors

2019-05-20 17:30:37,077 - [DEBUG] - from application in play-akka.actor.default-dispatcher-151 
[cors] filtering request to add cors

2019-05-20 17:32:21,291 - [DEBUG] - from application in play-akka.actor.default-dispatcher-150 
[cors] filtering request to add cors

2019-05-20 17:32:48,581 - [DEBUG] - from application in play-akka.actor.default-dispatcher-154 
[cors] filtering request to add cors

2019-05-20 17:37:36,451 - [DEBUG] - from application in play-akka.actor.default-dispatcher-155 
[cors] filtering request to add cors

2019-05-20 17:49:42,127 - [DEBUG] - from application in play-akka.actor.default-dispatcher-158 
[cors] filtering request to add cors

